{ config
, lib
, ...
}:
let
  colorScheme = config.colorScheme;
in
{
  options.programs.blink.theme = {
    enable = lib.mkEnableOption "blink dotfiles theme";

    path = lib.mkOption {
      type = lib.types.str;
      default = ".config/blink/colors.js";
      description = "Path to write blink theme to, relative to home directory";
    };
  };

  config = lib.mkIf config.programs.blink.theme.enable {
    # This won't be applied automatically, you'll need to manually import this theme in blink.
    # Copy the contents of the file generated by this into a github gist and import the raw file URL.
    # Based on https://github.com/niklaas/base16-blink/blob/master/templates/default.mustache
    home.file."${config.programs.blink.theme.path}".text = ''
      base00 = '#${colorScheme.palette.base00}';
      base01 = '#${colorScheme.palette.base01}';
      base02 = '#${colorScheme.palette.base02}';
      base03 = '#${colorScheme.palette.base03}';
      base04 = '#${colorScheme.palette.base04}';
      base05 = '#${colorScheme.palette.base05}';
      base06 = '#${colorScheme.palette.base06}';
      base07 = '#${colorScheme.palette.base07}';
      base08 = '#${colorScheme.palette.base08}';
      base09 = '#${colorScheme.palette.base09}';
      base0A = '#${colorScheme.palette.base0A}';
      base0B = '#${colorScheme.palette.base0B}';
      base0C = '#${colorScheme.palette.base0C}';
      base0D = '#${colorScheme.palette.base0D}';
      base0E = '#${colorScheme.palette.base0E}';
      base0F = '#${colorScheme.palette.base0F}';

      ansi00 = '#${colorScheme.palette.ansi00}';
      ansi01 = '#${colorScheme.palette.ansi01}';
      ansi02 = '#${colorScheme.palette.ansi02}';
      ansi03 = '#${colorScheme.palette.ansi03}';
      ansi04 = '#${colorScheme.palette.ansi04}';
      ansi05 = '#${colorScheme.palette.ansi05}';
      ansi06 = '#${colorScheme.palette.ansi06}';
      ansi07 = '#${colorScheme.palette.ansi07}';
      ansi08 = '#${colorScheme.palette.ansi08}';
      ansi09 = '#${colorScheme.palette.ansi09}';
      ansi10 = '#${colorScheme.palette.ansi10}';
      ansi11 = '#${colorScheme.palette.ansi11}';
      ansi12 = '#${colorScheme.palette.ansi12}';
      ansi13 = '#${colorScheme.palette.ansi13}';
      ansi14 = '#${colorScheme.palette.ansi14}';
      ansi15 = '#${colorScheme.palette.ansi15}';

      t.prefs_.set(
        'color-palette-overrides',
        [
          ansi00,
          ansi01,
          ansi02,
          ansi03,
          ansi04,
          ansi05,
          ansi06,
          ansi07,
          ansi08,
          ansi09,
          ansi10,
          ansi11,
          ansi12,
          ansi13,
          ansi14,
          ansi15,
        ]
      );

      t.prefs_.set('cursor-color', `''${base05}80`); // 80 makes it rgba and 50% opacity
      t.prefs_.set('foreground-color', base05);
      t.prefs_.set('background-color', base00);
    '';
  };
}
