{ ... }:

{
  imports = [
    ./aichat.nix
    ./aider.nix
    ./alacritty.nix
    ./bash.nix
    ./bat.nix
    ./blink.nix
    ./bottom.nix
    ./delta.nix
    ./direnv.nix
    ./fd.nix
    ./firefox.nix
    ./fish.nix
    ./fonts
    ./foot.nix
    ./fzf.nix
    ./git.nix
    ./helix.nix
    ./homer.nix
    ./kubernetes.nix
    ./k9s.nix
    ./lf.nix
    ./llama-swap.nix
    ./mako.nix
    ./neovim
    ./niri.nix
    ./ollama.nix
    ./ripgrep.nix
    ./rofi.nix
    ./starship.nix
    ./stylua.nix
    ./sway.nix
    ./tealdeer.nix
    ./tmux.nix
    ./waybar
    ./z-lua.nix
    ./zk.nix
  ];
}
